# Generated by Django 4.1.5 on 2023-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('animal', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
            ],
        ),
    ]
